### ISSUE TITLE
Gopherjs Implementation

### ISSUE THREAD

**Issue by dimiro1** [omeid/slurp-todo#1]
It would be nice if you implement the angular/javascript part in http://gopherjs.org/.

**Comment by omeid** [comment]
Gopherjs is very exciting but this project is trying to demonstrate how you can use Slurp for developing web apps in real world, using Gopher will over complicated it.

Of course, you're always welcome to fork this project and write a Gopher implementation of the frontend if you're interested, you will need to start with Gopherjs binding for Slurp which shouldn't be hard.
