### ISSUE TITLE
Error: can't make relative path on Windows

### ISSUE THREAD

**Issue by iampeterbanjo** [omeid/slurp-todo#2]
Hi,

On Windows, when I run `slurp init` I get a message similar to `can't make relative path $GOPATH/path/to/slurp-todo to C:\`. Could you please help me resolve this?

**Comment by omeid** [comment]
Sorry for the late reply. I don't have a working Windows machine to look at it now but I will look into in a next couple of days.

**Comment by omeid** [comment]
See the slurp#15.

Did it fix your problem?

**Comment by iampeterbanjo** [comment]
Thanks for the reply. Sorry I don't understand what you mean by "slurp#15"

**Comment by omeid** [comment]
Sorry, I should have linked properly. I meant the issue 15 at the slurp project: omeid/slurp#15

**Comment by iampeterbanjo** [comment]
Thanks I will try out those changes and let you know if they work for me :-)

**Comment by iampeterbanjo** [comment]
Sorry, I'm still getting the same error message 
`slurp init`
`2015/05/21 22:01:17 Rel: can't make \projects\golang\slurp-todo relative to \projects\golang\src`

**Comment by omeid** [comment]
Put the project under `$GOPATH/src/`. 

`\projects\golang\slurp-todo` should be `\projects\golang\src\slurp-todo` assuming `\projects\golang` is your $GOPATH.

**Comment by omeid** [comment]
If this has solved your problem. Please close this issue. :)

**Comment by iampeterbanjo** [comment]
Thanks - it works
